---
- name: Instalar certbot via APT
  ansible.builtin.apt:
    name:
      - certbot
    state: present
    update_cache: yes

- name: Verificar se o certificado já existe
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ project_domain }}/fullchain.pem
  register: cert_file

- name: Gerar o certificado se não existir
  ansible.builtin.command:
    cmd: >
      certbot certonly
        --standalone
        --non-interactive
        --agree-tos
        --email {{ certbot_email }}
        -d {{ project_domain }}
  when: not cert_file.stat.exists

- name: Garantir que o diretório /etc/letsencrypt exista
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    mode: '0755'
    owner: 'root'
    group: 'root'

- name: Gerar um grupo de parâmetros Diffie-Hellman (Esse Step demora bastante)
  ansible.builtin.command:
    cmd: openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048
    creates: /etc/letsencrypt/ssl-dhparams.pem

- name: Configurar a renovação do Certbot para usar o método webroot
  community.general.ini_file:
    path: "/etc/letsencrypt/renewal/{{ project_domain }}.conf"
    section: renewalparams
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0644'
  loop:
    - { option: 'authenticator', value: 'webroot' }
    - { option: 'webroot_path', value: '/var/www/html,' }

- name: Garantir que o timer de renovação automática do Certbot esteja ativo
  ansible.builtin.service:
    name: certbot.timer
    state: started
    enabled: yes
